//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captcha
    {
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Id_Fragment { get; set; }
        public Nullable<int> Id_Image { get; set; }
    }
}
