//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Inn { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Salesman { get; set; }
        public Nullable<bool> Buyer { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
