//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Manufacture_bdEntities1 : DbContext
    {
        private static Manufacture_bdEntities1 _context;

        public static Manufacture_bdEntities1 GetContext()
        {
            if (_context == null)
                _context = new Manufacture_bdEntities1();

            return _context;
        }
        public Manufacture_bdEntities1()
            : base("name=Manufacture_bdEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Captcha> Captchas { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Nomenclature> Nomenclatures { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<Production> Productions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Specification> Specifications { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UnitOfMeasurement> UnitOfMeasurements { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
