//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomenclature
    {
        public Nomenclature()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Prices = new HashSet<Price>();
            this.Productions = new HashSet<Production>();
            this.Specifications = new HashSet<Specification>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitOfMeasurementId { get; set; }
        public Nullable<bool> Product { get; set; }
        public Nullable<bool> Material { get; set; }
    
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
        public virtual ICollection<Specification> Specifications { get; set; }
    }
}
