//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public Production()
        {
            this.Specifications = new HashSet<Specification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NomenclatureId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Nomenclature Nomenclature { get; set; }
        public virtual ICollection<Specification> Specifications { get; set; }
    }
}
