//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public int Id { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<int> NomenclatureId_Material { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Nomenclature Nomenclature { get; set; }
        public virtual Production Production { get; set; }
    }
}
