//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkManufacture.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasurement
    {
        public UnitOfMeasurement()
        {
            this.Nomenclatures = new HashSet<Nomenclature>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AbbreviatedName { get; set; }
    
        public virtual ICollection<Nomenclature> Nomenclatures { get; set; }
    }
}
